FORMAT: 1A

# AirDC++ Web API

WORK IN PROGRESS

This documentation isn't compatible with the current stable versions of AirDC++/AirDC++ Web client



# Group Favorite directories


## Favorite directories [/favorite_directories/directories]

### List favorite directories [GET]

Get a list of all favorite directories.

Required permission: *settings_view*

+ Response 200 (application/json)
    + Attributes (array[Favorite directory])

### Get grouped paths [GET /favorite_directories/grouped_paths]

+ Response 200 (application/json)
    + Attributes (array[Grouped path])

## Favorite directory [/favorite_directories/directory]

### Create favorite directory [POST /favorite_directories/directory]

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes
        + path: /home/airdcpp/share/Linux/ (required) - Directory path
        + name: Linux (optional) - Virtual display name for the directory. Multiple paths can be added with the same name. Name will be determined from the path if not specified.
    
+ Response 200 (application/json)
    + Attributes (Favorite directory)

### Update favorite directory [PATCH /favorite_directories/directory/{directory_id}]

Update the specified fields of a favorite directory.

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes
        + name: Linux - Virtual display name for the directory. Multiple paths can be added with the same name.
    
+ Response 200 (application/json)
    + Attributes (Favorite directory)

### Get favorite directory [GET /favorite_directories/directory/{directory_id}]

Required permission: *settings_view*

Get a single directory by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Favorite directory)

### Remove favorite directory [DELETE /favorite_directories/directory/{directory_id}]

Required permission: *settings_edit*

+ Response 204


## Subscriptions [/favorite_directories/listener]

Required permission: *settings_view*

### Favorite directories updated [POST /favorite_hubs/listener/favorite_hub_updated]

+ Response 200 (application/json)
    + Attributes (array[Favorite directory])

## Data Structures

### Favorite directory

+ id: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ name: Linux - Virtual display name for the directory. Multiple paths can be added with the same name.
+ path: /home/airdcpp/share/Linux/ - Directory path




# Group Favorite hubs

Favorite hubs allow storing commonly used hubs that can be opened automatically on application startup. Various settings, such as user identification info and connectivity, can be customized on per-hub basis.

## Favorite hubs [/favorite_hubs/hubs/{start}/{count}]

### List favorite hubs [GET]

Get a list of favorite hubs

Required permission: *favorite_hubs_view*

+ Response 200 (application/json)
    + Attributes (array[Favorite hub])


## Favorite hub [/favorite_hubs/hub]

### Create favorite hub [POST]

Required permission: *favorite_hubs_edit*

+ Request (application/json)
    + Attributes (Favorite hub request)
    
+ Response 200 (application/json)
    + Attributes (Favorite hub)

### Update favorite hub [PATCH /favorite_hubs/hub/{hub_id}]

Update the specified fields of a favorite hub

Required permission: *favorite_hubs_edit*

+ Request (application/json)
    + Attributes (Favorite hub request)
    
+ Response 200 (application/json)
    + Attributes (Favorite hub)

### Get favorite hub [GET /favorite_hubs/hub/{hub_id}]

Required permission: *favorite_hubs_view*

Get a single hub by ID.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (Favorite hub)
    
### Remove favorite hub [DELETE /favorite_hubs/hub/{hub_id}]

Required permission: *favorite_hubs_edit*

+ Response 204


## Subscriptions [/favorite_hubs/listener]

Required permission: *favorite_hubs_view*
    
### Favorite hub created [POST /favorite_hubs/listener/favorite_hub_created]

+ Response 200 (application/json)
    + Attributes (Favorite hub)

### Favorite hub updated [POST /favorite_hubs/listener/favorite_hub_updated]

+ Response 200 (application/json)
    + Attributes (Favorite hub)

### Favorite hub created [POST /hubs/listener/favorite_hub_removed]

+ Response 200 (application/json)
    + Attributes (Favorite hub)

## Data Structures

### Favorite hub base

+ name: Demo hub
+ hub_description: Demo hub for AirDC++ Web Client
+ hub_url: adcs://myhub.com:6423
+ auto_connect: true (boolean) - Automatically connect to this hub on startup
+ nick: Developer - User nick (defaults to global value if not set)
+ user_description: Just writing scripts - User description (defaults to global value if not set)
+ nmdc_encoding: CP1252 - Iconv codepage to use for text conversion (NMDC hubs only, defaults to global value if not set)
+ connection_mode_v4 (Connectivity mode) - IPv4 connectivity mode (defaults to global value if not set)
+ connection_mode_v6 (Connectivity mode) - IPv6 connectivity mode (defaults to global value if not set)
+ connection_ip_v4: 89.255.248.35 - IPv4 address (defaults to global value if not set)
+ connection_ip_v6: 2a00:1a48:1261::168 - IPv6 address (defaults to global value if not set)

### Favorite hub (Favorite hub base)

+ id: 64723743 (number)
+ connect_state (object)
    + id: connected (enum[string])
        + connecting
        + connected
        + disconnected
    + str: Connected
    + current_hub_id: 5 (number) - Current hub session ID (0 = no session)
+ share_profile (Share profile basic) - Share profile to use (ADC hubs only, defaults to global value if not set)
+ has_password: true (boolean) - Specifies whether a password has been saved for this entry

### Favorite hub request (Favorite hub base)

+ share_profile: 7436564 (number)  - Share profile to use (ADC hubs only, defaults to global value if not set)
+ password: mystrongpassword


# Group Events

Events are used for displaying and logging informative messages and errors to the application user. Note that events are not bind to any specific context;
some entities, such as hubs, provide similar methods for showing information locally to the application user.

## Methods [/events]

### Get messages [GET /events/messages/{max_count}]

Get the latest event message. Returned messages are be sorted from oldest to newest.

Required permission: *events_view*

+ Parameters
    + max_count: 0 - Maximum number of messages to return (starts from the latest ones, 0 = unlimited)

+ Response 200 (application/json)
    + Attributes (array[Status message])

### Send event message [POST /events/message]

Send a new event message.

Required permission: *events_edit*

+ Request (application/json)
    + Attributes (Status message request)

+ Response 204

### Clear message cache [POST /events/clear]

Required permission: *events_edit*

+ Response 204

### Set all messages as read [POST /events/read]

Required permission: *events_edit*

+ Response 204

### Get message counts [GET /events/counts]

Required permission: *events_view*

+ Response 200 (application/json)
    + Attributes (Log message info)


## Subscriptions [/events/listener]

Required permission: *events_view*

### Message counts updated [POST /events/listener/event_counts]

+ Response 200 (application/json)
    + Attributes (Log message info)

### Message posted [POST /events/listener/event_message]

+ Response 200 (application/json)
    + Attributes (Status message)




# Group Filelists


## Filelist sessions [/filelists/sessions]

### Get filelist sessions [GET]

Get a list of all filelist sessions.

Required permission: *filelists_view*

+ Response 200 (application/json)
    + Attributes (array[Filelist])

## Filelist session [/filelists/session]

### Create remote filelist session [POST]

Queue filelist from an user.

Required permission: *filelists_edit*

+ Request (application/json)
    + Attributes
        + user (Hinted user, required)
        + list_path: /Share/Ubuntu/ (optional) - Initial filelist directory to load. Filelist root is loaded, if not specified.
            + Default: /
+ Response 200 (application/json)
    + Attributes (Filelist)

### Create local filelist session [POST /filelists/session/me]

Browse own share.

Required permission: *filelists_edit*

+ Request (application/json)
    + Attributes
        + share_profile: 643 (number, optional) - ID of the share profile to browse. Default profile is used if not specified.
+ Response 200 (application/json)
    + Attributes (Filelist)

### Get session [GET /filelists/session/{session_id}]

Required permission: *filelists_view*

Get a single filelist session by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Filelist)

### Remove session [DELETE /filelists/session/{session_id}]

Required permission: *filelists_edit*

+ Response 204


## Directory downloads [/filelists/directory_downloads]

### Get directory downloads [GET]

Get a list of all directory downloads.

Required permission: *download*

+ Response 200 (application/json)
    + Attributes (array[Directory download item])


### Create directory download [POST /filelists/directory_download]

Queue all content inside the specified location. Recursive partial filelist will be downloaded from ADC users and full list is used with NMDC users.

Required permission: *download*

+ Request (application/json)
    + Attributes (Download params)
        + user (Hinted user, required)
        + list_path: /Share/Ubuntu/ (required)
+ Response 200 (application/json)
    + Attributes (Directory download item)

### Remove directory download [DELETE /filelists/directory_download/{download_id}]

Required permission: *download*

+ Response 204


## Miscellaneous [/filelists]

### Match queue [POST /filelists/match_queue]

Match queue and add the user as source for matching files.

Required permission: *queue_edit*

+ Request (application/json)
    + Attributes
        + user (Hinted user, required)
        + list_path: /Share/Ubuntu/ (optional) - Directory to match from ADC (recursive partial list is used). Full filelist is always matched from NMDC users.
            + Default: /
+ Response 204


### Find NFO [POST /filelists/find_nfo]

Find a file with .nfo extension from the specified directory and open it for viewing. This method can only be used
with ADC users as recursive partial filelist is used.

Required permission: *view_files_edit*

+ Request (application/json)
    + Attributes
        + user (Hinted user, required)
        + list_path: /Share/Ubuntu/ (optional) - Directory to search the files from. Root ('/') is not allowed.
+ Response 204


## Subscriptions [/filelists/listener]

Required permission: *filelists_view*

All subscriptions from filelist entities are also available to be used across all sessions (add them with */filelists/listener/event_name*).

### Filelist session created [POST /filelists/listener/filelist_created]

+ Response 200 (application/json)

    + Attributes (Filelist)

### Filelist session removed [POST /filelists/listener/filelist_removed]

+ Response 200 (application/json)
    + Attributes (Filelist)

### Directory download added [POST /filelists/listener/filelist_directory_download_added]

+ Response 200 (application/json)
    + Attributes (Directory download item)

### Directory download removed [POST /filelists/listener/filelist_directory_download_removed]

+ Response 200 (application/json)
    + Attributes (Directory download item)

### Directory download processed [POST /filelists/listener/filelist_directory_download_processed]

+ Response 200 (application/json)
    + Attributes 
        + directory_download (Directory download item)
        + result (Queue directory bundle add info)

### Directory download failed [POST /filelists/listener/filelist_directory_download_failed]

+ Response 200 (application/json)
    + Attributes (Directory download item)
        + directory_download (Directory download item)
        + error: The directory is empty

## Data Structures

### Filelist

+ id: NJSHVYR4ZHCZFUEZNGA7M2D72S5AB4WQAMPBKFA
+ user (Hinted user)
+ location (Filelist item) - Information about the current location
+ share_profile (Share profile basic) - Only available for own filelist
+ state (Downloadable item state)
+ read: false (boolean) - Has the filelist been marked as read
+ partial_list: true (boolean)
+ total_files: 53356 (number)
+ total_size: 221767274 (number)


### Filelist item

+ id: 32 (number)
+ name: Ubuntu 14.04
+ type (Item type)
+ path: /home/airdcpp/share/Ubuntu/Ubuntu 14.04/ - Path in remote user's share
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ dupe (Dupe)
+ time: 1483611358 (number) - File creation/modification date (not always available)
+ size: 62523525626 (number) - Size in bytes (not always available for directories)
+ complete: true (boolean) - Whether the directory content has been downloaded


### Directory download item (Download params)

+ id: 427 (number)
+ list_path: /Linux/Ubuntu/Ubuntu 14.04/
+ user (Hinted user)



# Group Filelist entities

## Methods [/filelists/session/{session_id}]

### Get directory content [GET /filelists/session/{session_id}/items/{start}/{count}]

Get a list of all files and directories inside the current filelist location. If the directory content has not yet been loaded, an error will be returned.

Required permission: *filelists_view*

+ Response 200 (application/json)
    + Attributes (array[Filelist item])
    
+ Response 503

        Content of this directory is not yet available


### Change directory [POST /filelists/session/{session_id}/directory]

Change the current filelist directory.

Required permission: *filelists_view*

+ Request (application/json)
    + Attributes
        + list_path: /Share/Ubuntu/ (required)
        + reload: false (boolean, optional) - Force reloading of all existing content. This has no effect with full filelists.
            + Default: false
+ Response 204

### Set filelist as read [POST /filelists/session/{session_id}/read]

Required permission: *filelists_view*

+ Response 204


## Subscriptions [/filelists/session/{session_id}/listener]

Required permission: *filelists_view*

All subscriptions from filelist entities are also available to be used across all sessions (add them with */filelists/listener/event_name*).

### Filelist session updated [POST /filelists/listener/filelist_updated]

+ Response 200 (application/json)
    + Attributes (Filelist)




# Group Filesystem

## Methods [/filesystem]

### Create directory [POST /filesystem/directory]

Required permission: *filesystem_edit*

+ Request (application/json)
    + Attributes
        + path: /home/airdcpp/share/mynewdirectory/ (required) - Full path of the directory to create

+ Response 204

### List directory content [POST /filesystem/list_items]

Get a listing of items inside the supplied path

+ Request (application/json)
    + Attributes
        + path: /home/airdcpp/share/ (required) - Full path of the directory
        + directories_only: false (boolean, optional) - List directories only
            + Default: false
            
+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + name: myfile1
            + type: file (enum[string])
                + file
                + directory
            + size: 6382343 (number) - Size in bytes (available for files only)

### Get disk space information [POST /filesystem/disk_info]

Get disk space info for a set of directory paths

+ Request (application/json)
    + Attributes
        + paths: /home/airdcpp/share/dir/, /mnt/disk2/dir/ (array[string], required)
            
+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + path: /home/airdcpp/share/dir/
            + free_space: 81279320064 (number) - Free disk space in bytes
            + total_space: 109646487552 (number) - Total disk space in bytes
        + (object)
            + path: /mnt/disk2/dir/
            + free_space: 400443416576 (number) - Free disk space in bytes
            + total_space: 2953372659712 (number) - Total disk space in bytes



# Group Hashing





## Methods [/hash]

### Get database status [GET /hash/database_status]

Required permission: *settings_view*

+ Response 200 (application/json)
    + Attributes (Hash database status)


### Optimize database [POST /hash/optimize_database]

This operation will delete all hash information for files that aren't currently in share. If you are sharing files from network disks or from a removable storage, make sure that the files are currently shown in share (otherwise they have to be rehashed)

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes
        + verify: true (boolean, required) - Verify integrity of the databases. This will remove corrupted hash data entries.

+ Response 204

### Pause hashing [POST /hash/pause]

Pause all running hashers.

Required permission: *settings_edit*

+ Response 204

### Resume hashing [POST /hash/resume]

Resume all hashers in case they have been paused earlier.

Required permission: *settings_edit*

+ Response 204

### Stop hashing [POST /hash/stop]

Stop all hashers and clear the files that have been queued for hashing.

Required permission: *settings_edit*

+ Response 204


## Subscriptions [/hash/listener]

### Database status updated [POST /hash/listener/hash_database_status]

+ Response 200 (application/json)
    + Attributes (Hash database status)

### Hashing of a directory finished [POST /hash/listener/hasher_directory_finished]

+ Response 200 (application/json)
    + Attributes
        + path: /home/airdcpp/share/Ubuntu/ - Directory path
        + size: 43676423 (number) - Total size of the files that were hashed from this directory
        + files: 7 (number) - Number of files that were hashed from this directory
        + duration: 32574 (number) - Time in milliseconds that was spent on hashing the directory
        + hasher_id: 0 (number) - ID of the hasher

### Hashing finished [POST /hash/listener/hasher_finished]

A single hasher has finished.

+ Response 200 (application/json)
    + Attributes
        + size: 436764423 (number) - Total size of the files that were hashed
        + files: 52 (number) - Number of files that were hashed
        + directories: 4 (number) - Number of directories that were hashed
        + duration: 6332574 (number) - Time in milliseconds that was spent on hashing the items
        + hashed_id: 0 (number) - ID of the hasher


### Hash statistics [POST /hash/listener/hash_statistics]

Only the properties that have changed since the last event are sent.

+ Response 200 (application/json)
    + Attributes
        + hash_speed: 4367623 (number) - Total current hashing speed, bytes per second
        + hash_bytes_left: 52 (number) - Total number of bytes remaining to be hashed
        + hash_files_left: 4 (number) - Total number of files remaining to be hashed
        + hashers: 2 (number) - Number of hashing threads running


## Data Structures

### Hash database status

+ maintenance_running: false (boolean) - Whether database optimization is currently running
+ file_index_size: 2143207 (number) - Size of the file index database on disk (bytes)
+ hash_store_size: 446720235 (number) - Size of the hash store database on disk (bytes)



# Group Hubs

Hub API provides methods for communicating with hubs

## Hub sessions [/hubs/sessions]

### Get a list of all hub sessions [GET]

Get a list of web server session

Required permission: *hubs_view*

+ Response 200 (application/json)
    + Attributes (array[Hub])

## Hub session [/hubs/session]

### Create session [POST]

Create a new hub session.

Required permission: *hubs_edit*

+ Request (application/json)
    + Attributes
        + hub_url: adcs://myhub.com:6423 (required) - Full URL of the hub to connect to
+ Response 200 (application/json)
    + Attributes (Hub)

### Get session [GET /hubs/session/{session_id}]

Required permission: *hubs_view*

Get a single session by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Hub)

### Remove session [DELETE /hubs/session/{session_id}]

Required permission: *hubs_edit*

+ Response 204


## Miscellaneous [/hubs]

### Find session by URL [POST /hubs/find_by_url]

Get a single hub session by URL (exact match).

+ Request (application/json)
    + Attributes
        + hub_url: adcs://myhub.com:6423 (required)

+ Response 200 (application/json)
    + Attributes (Hub)

### Stats [GET /hubs/stats]

Return various statistics about the connected hubs and their users

+ Response 200 (application/json)

### Send chat message [POST /hubs/message]

Send a public chat message message to specified hubs.

Required permission: *hubs_send*

+ Request (application/json)
    + Attributes 
        + message (Chat message request, required)
        + hub_urls: adcs://myhub.com:6423, mynmdchub.com (array, optional) - A list of hub URLs where the message should be sent to. The message will be sent to all connected hubs if this field is not provided.

+ Response 200 (application/json)
    + Attributes
        + sent: 1 (number) - Number of messages that were sent successfully. Message won't be sent to URLs without a corresponding hub session or hubs that are not in a connected state.

### Send status message [POST /hubs/status]

Send a status message message that is only shown locally in specified hubs.

Required permission: *hubs_edit*

+ Request (application/json)
    + Attributes 
        + message (Status message request, required)
        + hub_urls: adcs://myhub.com:6423, mynmdchub.com (array, optional) - A list of hub URLs where the message should be shown. The message will be shown in all hubs if this field is not provided.

+ Response 200 (application/json)

    + Attributes
        + sent: 1 (number) - Number of messages that were sent successfully. Message won't be sent to URLs without a corresponding hub session.

## Subscriptions [/hubs/listener]

Required permission: *hubs_view*

All subscriptions from hub entities are also available to be used across all sessions (add them with */hubs/listener/event_name*).

### Hub session created [POST /hubs/listener/hub_created]

+ Response 200 (application/json)

    + Attributes (Hub)

### Hub session removed [POST /hubs/listener/hub_removed]

+ Response 200 (application/json)
    + Attributes (Hub)


## Data Structures

### Hub

+ id: 5 (number)
+ hub_url: adcs://myhub.com:6423
+ connect_state (object)
    + id: connected (enum[string])
        + connecting - Connecting to the hub in processed
        + password - Password was requested by the hub and there is no saved one. The 'password' can be used to post one.
        + connected
        + keyprint_mismatch - Keyprint specified in the hub URL doesn't match the actual hub certificate keyprint
        + disconnected
        + redirect - Redirect was requested to another hub (see state data)
    + str: Connected
    + data - Possible state-related data
        + hub_url: mynmdchub.com - Redirect url ('redirect' state only)
+ identity (object)
    + name: Demo hub
    + description: Demo hub for AirDC++ Web Client
+ share_profile (Share profile)
+ favorite_hub: 64723743 (number) - Favorite hub ID (0 = no favorite hub)
+ message_counts (Chat message info)
+ encryption (Encryption, optional) - Available only for connected ADCS hubs

### Hub counts

+ share_size: 832572352 (number)
+ user_count: 3 (number)


# Group Hub sessions

## Methods [/hubs/session/{id}]

### Get users [GET /hubs/session/{session_id}/users/{start}/{count}]

Required permission: *hubs_view*

+ Response 200 (application/json)
    + Attributes (array[Hub user])

### Get user [GET /hubs/session/{session_id}/user/{cid}]

Get user information by CID.

Required permission: *hubs_view*

+ Response 200 (application/json)
    + Attributes (Hub user)

### Get messages [GET /hubs/session/{session_id}/messages/{max_count}]

Required permission: *hubs_view*

+ Parameters
    + max_count: 0 - Maximum number of messages to return (0 = unlimited)

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + chat_message (Chat message)
        + (object)
            + status_message (Status message)

### Send chat message [POST /hubs/session/{session_id}/message]

Send a public chat message to this hub.

Required permission: *hubs_send*

+ Request (application/json)
    + Attributes (Chat message request)

+ Response 204

### Send status message [POST /hubs/session/{session_id}/status]

Send a status message message that is only shown locally in this hub.

Required permission: *hubs_edit*

+ Request (application/json)
    + Attributes (Status message request)

+ Response 204

### Clear message cache [POST /hubs/session/{session_id}/clear]

Required permission: *hubs_edit*

+ Response 204

### Set all messages as read [POST /hubs/session/{session_id}/read]

Required permission: *hubs_view*

+ Response 204


### Send password [POST /hubs/session/{session_id}/password]

Set the hub password. This should be used only when the hub is in *password* state. The password will be reused during the session lifetime in case the application gets disconnected from the hub.

Required permission: *hubs_edit*

+ Request (application/json)
    + Attributes 
        + password: myuniquepassword (required)

+ Response 204

### Follow redirect [POST /hubs/session/{session_id}/redirect]

Follow the redirection requested by the hub. This should be used only when the hub is in *redirect* state. 

Required permission: *hubs_edit*

+ Response 204

### Reconnect [POST /hubs/session/{session_id}/reconnect]

Reconnect to the hub.

Required permission: *hubs_edit*

+ Response 204

### Favorite [POST /hubs/session/{session_id}/favorite]

Save the hub in favorites.

Required permission: *hubs_edit*

+ Response 200 (application/json)
    + Attributes (Favorite hub)

### Get user and share counts [GET /hubs/session/{session_id}/counts]

Get the current user and share counts.

Required permission: *hubs_edit*

+ Response 200 (application/json)
    + Attributes (Hub counts)


## Subscriptions [/hubs/session/{id}/listener]

Required permission: *hubs_view*

All subscriptions from hub entities are also available to be used across all sessions (add them with */hubs/listener/event_name*).

### Session updated [POST /hubs/session/{id}/listener/hub_updated]

+ Response 200 (application/json)
    + Attributes (Hub)

### User/share counts updated [POST /hubs/session/{id}/listener/hub_counts_updated]

+ Response 200 (application/json)
    + Attributes (Hub counts)

### Chat message received [POST /hubs/session/{id}/listener/hub_message]

+ Response 200 (application/json)
    + Attributes (Chat message)

### Status message received [POST /hubs/session/{id}/listener/hub_status]

+ Response 200 (application/json)
    + Attributes (Status message)

### Hub user connected [POST /hubs/session/{id}/listener/hub_user_connected]

+ Response 200 (application/json)
    + Attributes (Hub user)

### Hub user updated [POST /hubs/session/{id}/listener/hub_user_updated]

Only the user ID and possibly changed fields are sent 

+ Response 200 (application/json)
    + Attributes (Hub user)

### Hub user disconnected [POST /hubs/session/{id}/listener/hub_user_disconnected]

+ Response 200 (application/json)
    + Attributes (Hub user)




# Group Private chat


//Hub API provides methods for communicating with hubs

## Private chat sessions [/private_chat/sessions]

### Get a list of all private chat sessions [GET]

Required permission: *private_chat_view*

+ Response 200 (application/json)
    + Attributes (array[Private chat])

## Private chat session [/private_chat/session]

### Create session [POST]

Create a new API session by providing the web user credentials.

Required permission: *private_chat_edit*

+ Request (application/json)
    + Attributes
        + user (Hinted user base, required)
+ Response 200 (application/json)
    + Attributes (Private chat)

### Get session [GET /private_chat/session/{session_id}]

Required permission: *private_chat_view*

Get a single session by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Private chat)

### Remove session [DELETE /private_chat/session/{session_id}]

Required permission: *private_chat_edit*

+ Response 204

## Miscellaneous [/private_chat]

### Send chat message [POST /private_chat/message]

Send private chat message message to a specific user. This should generally be used for announcement-like messages only as private chat sessions are more suitable for bidirectional chatting.

Required permission: *private_chat_send*

+ Request (application/json)
    + Attributes 
        + message (Chat message request, required)
        + user (Hinted user base, required)
        + echo: false (boolean, optional) - Echo the sent message back to me. This will always cause a new private chat session to be created and allows the message to be logged. Note that a private chat session will also be created if the other users replies to your message (or sends an away message).
            + Default: false

+ Response 204


## Subscriptions [/private_chat/listener]

Required permission: *private_chat_view*

All subscriptions from private chat entities are also available to be used across all sessions (add them with */private_chat/listener/event_name*).

### Private chat session created [POST /private_chat/listener/private_chat_created]

+ Response 200 (application/json)

    + Attributes (Private chat)

### Private chat session removed [POST /private_chat/listener/private_chat_removed]

+ Response 200 (application/json)
    + Attributes (Private chat)


## Data Structures

### Private chat

+ id: NJSHVYR4ZHCZFUEZNGA7M2D72S5AB4WQAMPBKFA
+ user (Hinted user)
+ ccpm_state (object)
    + id: connected (enum[string])
        + connecting
        + connected
        + disconnected
    + str: Connected
    + encryption (Encryption, optional) - Available only with connected CCPM connections
+ message_counts (Chat message info)



# Group Private chat sessions

## Methods [/private_chat/session/{id}]

### Get messages [GET /private_chat/session/{session_id}/messages/{max_count}]

Required permission: *private_chat_view*

+ Parameters
    + max_count: 0 - Maximum number of messages to return (0 = unlimited)

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + chat_message (Chat message)
        + (object)
            + status_message (Status message)

### Send chat message [POST /private_chat/session/{session_id}/message]

Send private message to the user.

Required permission: *private_chat_send*

+ Request (application/json)
    + Attributes (Chat message request)

+ Response 204

### Send status message [POST /private_chat/session/{session_id}/status]

Send a status message that is only shown locally in this chat session.

Required permission: *private_chat_edit*

+ Request (application/json)
    + Attributes (Status message request)

+ Response 204

### Clear message cache [POST /private_chat/session/{session_id}/clear]

Required permission: *private_chat_edit*

+ Response 204

### Set all messages as read [POST /private_chat/session/{session_id}/read]

Required permission: *private_chat_view*

+ Response 204

### Initiate CCPM connection [POST /private_chat/session/{session_id}/ccpm]

Establish an encrypted client-to-client private messaging channel. CCPM is available only with users having the *ccpm* flag.

Required permission: *private_chat_edit*

+ Response 204

### Disconnect CCPM connection [DELETE /private_chat/session/{session_id}/ccpm]

Disconnect encrypted client-to-client private messaging channel. Messages will be delivered through the hub after the channel has been disconnected.

Required permission: *private_chat_edit*

+ Response 204


## Subscriptions [/private_chat/session/{id}/listener]

Required permission: *private_chat_view*

All subscriptions from private chat entities are also available to be used across all sessions (add them with */private_chat/listener/event_name*).

### Session updated [POST /private_chat/session/{id}/listener/private_chat_updated]

+ Response 200 (application/json)
    + Attributes
        + session (Private chat)

### Chat message received [POST /private_chat/session/{id}/listener/private_chat_message]

+ Response 200 (application/json)

    + Attributes (Chat message)
        
### Status message received [POST /private_chat/session/{id}/listener/private_chat_status]

+ Response 200 (application/json)
    + Attributes (Status message)




# Group Queue

## Bundles [/queue/bundles/{start}/{count}]

### Get bundles [GET]

Required permission: *queue_view*

+ Response 200 (application/json)
    + Attributes (array[Queue bundle])

### Remove finished bundles [POST /queue/bundles/remove_finished]

Required permission: *queue_edit*

Remove all bundles that have finished downloading.

+ Response 200 (application/json)
    + Attributes
        + count: 4 (number) - Number of bundles that were removed

### Set bundle priorities [POST /queue/bundles/priority]

Required permission: *queue_edit*

Change the priority of all queued bundles.

+ Request (application/json)
    + Attributes
        + priority (Queue priority ID, required)

+ Response 204

## Bundle [/queue/bundle]

### Create file bundle [POST /queue/bundle/file]

Required permission: *queue_edit*

+ Request (application/json)
    + Attributes
        + target_name: Ubuntu 16.04.iso (required)
        + target_directory: /home/airdcpp/share/Ubuntu/ (required)
        + priority (Queue priority ID, optional)
        + size: 576345234 (number) - File size in bytes (required)
        + time: 42421412 - Original file creation/modify time (optional)
        + tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y (required)
        + user (Hinted user base, optional)

+ Response 200 (application/json)
    + Attributes (Queue bundle add info)

### Create directory bundle [POST /queue/bundle/directory]

Note: this method is generally meant for importing content from external sources into queue. When queueing directories from other users, you should generally use the respective API methods in Filelist and Search APIs.

Required permission: *queue_edit*

+ Request (application/json)
    + Attributes (Download params)
        + time: 42421412 - Original directory creation/modify time (optional)
        + files (array)
            + name: `CD1/Ubuntu 16.04.iso` (required) - File name that may also contain subdirectories relative to the main bundle path
            + priority (Queue priority ID, optional) - File priority
            + size: 576345234 - File size in bytes (number, required)
            + time: 42421412 - Original file creation/modify time (optional)
            + tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y (required)

+ Response 200 (application/json)
    + Attributes (Queue directory bundle add info)

### Get bundle [GET /queue/bundle/{id}]

Required permission: *queue_view*

+ Response 200 (application/json)
    + Attributes (Queue bundle)

### Update bundle properties [PATCH /queue/bundle/{id}]

Required permission: *queue_edit*

+ Request (application/json)
    + Attributes
        + priority (Queue priority ID, optional)
        + auto_priority: false (optional)

+ Response 200 (application/json)
    + Attributes (Queue bundle)

### Remove bundle [POST /queue/bundle/{id}/remove]

Required permission: *queue_edit*

+ Request (application/json)
    + Attributes
        + remove_finished: false (boolean, optional) - Remove finished bundle files
            + Default: false

+ Response 204

### Get bundles [GET /queue/bundle/{id}/files/{start}/{count}]

Required permission: *queue_view*

+ Response 200 (application/json)
    + Attributes (array[Queue file])

### Get bundle sources [GET /queue/bundle/{id}/sources]

Required permission: *queue_view*

+ Response 200 (application/json)
    + Attributes (array[Queue bundle source])

### Remove bundle source [DELETE /queue/bundle/{id}/source/{cid}]

Required permission: *queue_edit*

+ Response 200 (application/json)
    + Attributes
        + count: 4 (number) - Number of files from which the source was removed

### Search bundle for alternates [POST /queue/bundle/{id}/search]

Searches individual bundle files for alternatives. The number of files to search for depends on the bundle structure.

Required permission: *queue_edit*

+ Response 200 (application/json)
    + Attributes
        + sent: 4 (number) - Number of individual bundle files that were searched for


## Generic methods [/queue]

### Get dupe paths [POST /queue/find_dupe_paths]

Get local paths for file/folder name/path or a TTH value.

+ Request (application/json)
    + Attributes (object, required)
        + One of
            + path: /apps/Ubuntu/CD1/ - Individual file/folder name or path. Partial paths may also be supplied (e.g. Ubuntu/CD1/). The application will attempt to determine the relevant section from end to match.
            + tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y - File TTH

+ Response 200 (application/json)
    + Attributes (array[object])
        + (object)
            + name: Videos
            + paths: /home/airdcpp/share/Videos/, /mnt/disk2/share/Videos/ (array[string])

### Remove source [DELETE /queue/source/{cid}]

Remove source from all queued files.

Required permission: *queue_edit*

+ Response 200 (application/json)
    + Attributes
        + count: 4 (number) - Number of files from which the source was removed

### Remove file by path [DELETE /queue/remove_file]

Remove source from all queued files.

Required permission: *queue_edit*

+ Response 204


## Subscriptions [/queue/listener]

### Bundle added [POST /queue/listener/bundle_added]

+ Response 200 (application/json)

    + Attributes (Queue bundle)
    
### Bundle updated [POST /queue/listener/bundle_updated]

You may also use the following listeners for specific types of events:

- bundle_content - bundle content was changed
- bundle_priority - bundle priority was changed
- bundle_sources  - bundle sources were changed
- bundle_status - bundle status was changed
- bundle_tick - download progress was changed

+ Response 200 (application/json)

    + Attributes (Queue bundle)
    
### Bundle removed [POST /queue/listener/bundle_removed]

+ Response 200 (application/json)

    + Attributes (Queue bundle)


## Data Structures

### Queue bundle add info

+ id: 83425443 (number) - Bundle ID
+ merged: true (boolean) - Indicates whether this is a new bundle or was the queued item merged into an existing one

### Queue directory bundle add info

+ files_queued: 14 (number) - Number of new files that were queued successfully
+ files_updated: 34 (number) - Number of existing files that were possibly updated (new source was added)
+ files_failed: 1 (number) - Number of files that could not be queued
+ error: `A file with different TTH root already exists in the queue (affected file(s): Ubuntu 14.04.nfo)`
+ bundle (Queue bundle add info) 

### Queue item base

+ size: 62523525626 (number) - Size in bytes
+ downloaded_bytes: 4521124 (number)
+ priority (Queue priority)
+ time_added: 65235235 (number)
+ time_finished: 0 (number) - Time when the item was finished (0 = not finished)
+ speed: 5234324 (number) - Current download speed, bytes per second
+ seconds_left: 632576 (number) - Seconds left based on the current download speed
+ sources (Queue source info)

### Queue bundle (Queue item base)

+ id: 83425443
+ name: Ubuntu
+ target: /home/airdcpp/share/Ubuntu/
+ type (Item type)
+ status
    + id: queued (enum[string])
         + new - Not added in queue yet
         + queued - Queued
         + recheck
         + downloaded
         + moved
         + download_failed
         + scan_failed
         + finished
         + hashing
         + hash_failed
         + hashed
         + shared
    + failed: false (boolean) - Whether the bundle is in an error state
    + finished: false (boolean) - Whether the bundle has finished downloading
    + str: `Running (42.3%)`

### Queue file (Queue item base)

+ id: 23425443
+ name: Ubuntu 14.04.iso
+ target: /home/airdcpp/share/Ubuntu/Ubuntu 14.04.iso
+ type (File type)
+ bundle: 83425443 (number) - Bundle (0 = no bundle)
+ status
    + str: `Running (42.3%)`
    + finished: false (boolean)
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y - File TTH

### Queue bundle source

+ user (Hinted user)
+ last_speed: 57453654 (number) - Last known total speed from the user, bytes per second
+ files: 53 (number) - Bundle files remaining from this source
+ size: 734234563 (number) - Total number of bytes remaining from this source

### Queue source info

+ online: 2 (number) - Number of sources online
+ total: 3 (number) - Total number of item sources
+ str: 2/3 online

### Queue priority

+ id (Queue priority ID)
+ str: Paused
+ auto: false (boolean) - Auto priority state




# Group Searching


Hub API provides methods for communicating with hubs

## Search instances [/search/instances]

### Get a list of all search instances [GET]

Required permission: *search*

+ Response 200 (application/json)
    + Attributes (array[Search instance])



## Search instance [/search/instance]

### Create instance [POST]

Required permission: *search*

+ Request (application/json)
    + Attributes
        + expiration_minutes: 30 (optional) - Time in minutes after which the instance will be removed automatically (0 = no expiration)
            + Default: 30
+ Response 200 (application/json)
    + Attributes (Search instance)

### Get instance [GET /search/instance/{instance_id}]

Required permission: *search*

Get a single instance by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Search instance)

### Remove instance [DELETE /search/instance/{instance_id}]

Required permission: *search*

+ Response 204

## Miscellaneous [/search]

### Search types [GET /search/types]

Return all search types

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + id: 1
            + str: Audio
            + extensions: ape, flac, m4a, mid, mp3, mpc, ogg, ra, wav, wma
            + default_type: true (boolean) - This is an inbuilt type that can't be removed (extensions can still be modified)

## Subscriptions [/search/listener]

Required permission: *search*

All subscriptions from search instances are also available to be used across all instances (add them with */search/listener/event_name*).


## Data Structures

### Search instance

+ id: 0 (number)
+ expiration: 600 (number) - Time in milliseconds until the instance expires

### Grouped search result

+ id: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ name: dir
+ relevance: 1.34 (number) - Calculated item relevance based on the result name and number of hits
+ hits: 4 (number) - Number of users (child users) from who the item was found
+ user (Hinted user) - Base user from who the result name and path were picked from
+ type (Item type)
+ path: /home/airdcpp/share/dir/ - Path in remote user's share
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ dupe (Dupe)
+ time: 1483611358 (number) - File creation/modification date. The oldest found date is shown for parent results. Not available for NMDC results.
+ slots (Slot count) - Accummulated slot counts from users
+ connection: 42500000 (number) - Accummulated connection speed from users, bytes per second
+ size: 62523525626 (number) - Size in bytes (not available for NMDC directory results)

### Child search result

+ id: 427 (number)
+ path: /Linux/Ubuntu 14.04/ - Path in remote user's share
+ user (Hinted user)
+ slots (Slot count)
+ time: 1483611358 (number) - File creation/modification date.
+ connection: 12500000 (number)  - Connection speed, bytes per second
+ ip (IP)

### Slot count

+ free: 2 (number)
+ total: 11 (number)
+ str: 2/11



# Group Search instances

## Methods [/search/instance/{instance_id}]

### Perform hub search [POST /search/instance/{instance_id}/hub_search]

Search files from all connected (or separately specified) hubs.

Required permission: *search*

+ Request (application/json)
    + Attributes 
        + query (Search query, required)
        + priority (Priority ID, optional) - Priority in the outgoing search queue. Priorities above 'Normal' shouldn't be used for background searches to avoid delaying manual searches performed from the UI. Defaults to 'Low'.
            + Default: 2
        + hub_urls: adcs://myhub.com:6423, mynmdchub.com (optional) - A list of hub URLs where the search should be sent to. Search will be sent to all connected hubs if this field is not provided.

+ Response 200 (application/json)
    + Attributes
        + queue_time: 5000 - Current queue time for this search in milliseconds. Given that this is not a manual search, higher priority searches that are queued after this one may increase the waiting time even more.
        + search_id: 643345 - An individual search ID for this query
        + sent: 3 - Number of hubs for which the search was queued

### Perform user search [POST /search/instance/{instance_id}/user_search]

Search files from an individual user. The search will be sent instantly without queueing.

This method can be used with ADC users only.

Required permission: *search*

+ Request (application/json)
    + Attributes 
        + query (Search query, required)
        + user (Hinted user, required) 

+ Response 204

### Get results [GET /search/instance/{instance_id}/results/{start}/{max_count}]

Get results for the previously posted search query.

Required permission: *search*

+ Response 200 (application/json)
    + Attributes (array[Grouped search results])

### Download result [POST /search/instance/{instance_id}/result/{result_id}/download]

Queue the specified result. If there is a large number of users sharing the same item, the application will pick the fastest ones automatically.

Required permission: *download*

+ Request (application/json)
    + Attributes (Download params)
        + target_name: Ubuntu (optional) - Name of the search result will be used if not specified

+ Response 200 (application/json)
    + Attributes
        + One of (object)
            + bundle_info (Queue bundle add info) - Response for file downloads
            + directory_downloads (array[Directory download item]) - Response for directory downloads


### Get child user results [GET /search/instance/{instance_id}/result/{result_id}/children]

Get a list of individual user results.

Required permission: *search*

+ Response 200 (application/json)
    + Attributes (array[Child search result])


## Subscriptions [/search/instance/{id}/listener]

Required permission: *search*

All subscriptions from search instances are also available to be used across all instances (add them with */search/listener/event_name*).

### Parent result added [POST /search/instance/{id}/listener/search_result_added]

+ Response 200 (application/json)
    + Attributes (Grouped search result)

### Parent result updated [POST /search/instance/{id}/listener/search_result_updated]

+ Response 200 (application/json)
    + Attributes (Grouped search result)

### User result received [POST /search/instance/{id}/listener/search_user_result]

+ Response 200 (application/json)
    + Attributes (Child search result)



# Group Sessions

Session API provides methods for authentication and generic session management

## Session [/session/auth]

### Create session [POST]

Create a new API session by providing the web user credentials.

+ Request (application/json)
    + Attributes
        + username: user1 (required)
        + password: password (required)
        + max_inactivity: 60 (optional) - Time in minutes after which the session is invalidated if there is no activity. Note that sessions with a connected websocket won't expire. The default session inactivity timeout can be configured from web server settings.
            + Default: 20
+ Response 200 (application/json)
    + Attributes
        + token: `25793d1e-6d48-407c-9c27-a9dcbd2e1188` - Authorization token
        + system_info (System info) - Generic information about the system that the application is running on
        + user (Web user) - Current web user
        + wizard_pending: false - Whether completion of the initial configuration wizard is pending

### Remove session [DELETE]

Invalidate the current session

+ Response 204

### Get current session [GET /session/session]

Get the current session entity

+ Response 200 (application/json)
    + Attributes (Session)

### Socket [POST /session/socket]

Associate socket with an existing session.

+ Request (application/json)
    + Attributes
        + authorization: `25793d1e-6d48-407c-9c27-a9dcbd2e1188` (required) - Session identifier token

+ Response 204


### Activity [POST /session/activity]

Notify the application about user activity or ensure that HTTP session won't expire.

+ Request (application/json)
    + Attributes
        + user_active: false (optional)
        
          Specifies whether the user has been active since the last activity report. This information is used for calculating the away state of the application. Scripts that don't involve user interaction shouldn't provide this attribute.
        
          + Default: false

+ Response 204


## Sessions [/session/sessions]
        
### Get sessions [GET]

Get a list of web server session

Required permission: *admin*

+ Response 200 (application/json)
    + Attributes (array[Session])

## Subscriptions [/session/listener]

Required permission: *admin*

### Session created [POST /session/listener/session_created]

+ Response 200
    + Attributes
        + session (Session)

### Session removed [POST /session/listener/session_removed]

+ Response 200 (application/json)
    + Attributes
        + session (Session)

## Data Structures

### Session

+ id: 143743423 (number) - Session ID (this is not the auth token)
+ ip: [::1] - Last IP address used for the connection (IPv4/IPv6)
+ last_activity: 6236 - Milliseconds since last session activity
+ type: secure (enum[string])
  + basic_http
  + plain
  + secure
+ user (Web user) - Web user account used for authentication


# Group Settings


## Data Structures

### Connectivity mode (enum[number])

+ `-1` - Disabled
+ 0 - Active mode (no router or manual router configuration)
+ 1 - Active mode with NAT-PMP / UPnP (let the client configure my router)
+ 2 - Passive mode (last resort - has serious limitations)


# Group Share

## Excludes [/share/excludes]

### List excluded paths [GET]

Required permission: *share_view*

+ Response 200 (application/json)
    + Attributes (array[string])
        + /home/airdcpp/share/Videos/secret/
        + /mnt/disk2/share/Videos/secret/

### Add excluded path [POST /share/exclude/add]

Required permission: *share_edit*

+ Request (application/json)
    + Attributes
        + path: /home/airdcpp/share/Videos/secret/ (required) - Path to exclude

+ Response 204

### Remove excluded path [POST /share/exclude/remove]

Required permission: *share_edit*

+ Request (application/json)
    + Attributes
        + path: /home/airdcpp/share/Videos/secret/ (required) - Excluded path to remove

+ Response 204

## Generic methods [/share]

### Grouped share roots [GET /share/grouped_root_paths]

+ Response 200 (application/json)
    + Attributes (array[Grouped path])

### Refresh whole share [POST /share/refresh]

Required permission: *share_edit*

+ Response 204

### Refresh real paths [POST /share/refresh/paths]

Required permission: *share_edit*

+ Request (application/json)
    + Attributes
        + paths: /home/airdcpp/share/Videos/video1/, /home/airdcpp/share/Videos/video2/ (required) - Paths to refresh (they all must be found from share)

+ Response 204

### Refresh virtual path [POST /share/refresh/virtual]

Required permission: *share_edit*

+ Request (application/json)
    + Attributes
        + path: /Videos/ (required) - Virtual path to refresh

+ Response 204

### Get dupe paths [POST /share/find_dupe_paths]

Get local paths for file/folder name/path or a TTH value.

+ Request (application/json)
    + Attributes (object, required)
        + One of
            + path: /apps/Ubuntu/CD1/ - Individual file/folder name or path. Partial paths may also be supplied (e.g. Ubuntu/CD1/). The application will attempt to determine the relevant section from end to match.
            + tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y - File TTH

+ Response 200 (application/json)
    + Attributes (array)
        + /home/airdcpp/share/Ubuntu/CD1/
        + /mnt/disk2/share/Ubuntu/CD1/

### Search files [POST /share/search]

Search for shared files.

+ Request (application/json)
    + Attributes (object, required)
        + query (Search query, required)
        + share_profile (number, optional) - Items will be searched for from whole share if no profile is specified.

+ Response 200 (application/json)
    + Attributes (array[Share item])


## Subscriptions [/share/listener]

Required permission: *settings_view*

### Share refreshed [POST /share/listener/share_refreshed]

Fired when share refresh (partial or full refresh) has been completed.

+ Response 200 (application/json)
    + Attributes
        + real_paths: /home/airdcpp/share/, /mnt/disk2/share/ (array)
        + type (enum[string])
            + add_directory - A new share directory was scanned and is now visible in shared
            + add_bundle - Downloaded bundle was added in share
            + refresh_all - Whole share was refreshed
            + refresh_directories - Custom share paths were refreshed
            + refresh_incoming - Share roots marked as incoming were refreshed

### Excluded path added [POST /share/listener/share_exclude_added]

+ Response 200 (application/json)
    + Attributes 
        + path: /home/airdcpp/share/Videos/secret/

### Excluded path removed [POST /share/listener/share_exclude_removed]

+ Response 200 (application/json)
    + Attributes 
        + path: /home/airdcpp/share/Videos/secret/

## Data Structures

### Share item

+ id: 427 (number)
+ name: Ubuntu 14.04
+ virtual_path: /Linux/Ubuntu 14.04/
+ real_paths: /home/airdcpp/share/Linux/Ubuntu 14.04/ (array)
+ type (Item type)
+ time: 1483611358 (number) - Modification date
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ size: 62523525626 (number) - Size in bytes



# Group Share profiles

Share profiles can be used to share different content in ADC hubs (hub preferences are configured from favorite hubs). NMDC hubs will always use the default share profile.

## Profiles [/share_profiles/profiles]

### List share profiles [GET]

+ Response 200 (application/json)
    + Attributes (array[Share profile])

### Add share profile [POST /share_profiles/profile]

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes
        + name: Video only (required) - Name of the profile

+ Response 200 (application/json)
    + Attributes (Share profile)

### Get share profile [GET /share_profiles/profile/{profile_id}]

+ Response 200 (application/json)
    + Attributes (Share profile)

### Get default share profile [GET /share_profiles/profile/default]

+ Response 200 (application/json)
    + Attributes (Share profile)

### Update share profile [PATCH /share_profiles/profile/{profile_id}]

Required permission: *settings_edit*

+ Parameters
    + profile_id: 7453466 (required)

+ Request (application/json)
    + Attributes
        + name: Videos only - Name of the profile

+ Response 200 (application/json)
    + Attributes (Share profile)

### Set default share profile [POST /share_profiles/profile/{profile_id}/default]

Set this profile as default. 

Required permission: *settings_edit*

+ Response 204

### Remove share profile [DELETE /share_profiles/profile/{profile_id}]

Note that the current default profile can't be removed (you must set a new default profile first).

Required permission: *settings_edit*

+ Parameters
    + profile_id: 7453466 (required)

+ Response 204


## Subscriptions [/share_profiles/listener]

### Share profile added [POST /share_profiles/listener/share_profile_added]

+ Response 200 (application/json)
    + Attributes (Share profile)

### Share profile updated [POST /share_profiles/listener/share_profile_updated]

+ Response 200 (application/json)
    + Attributes (Share profile)

### Share profile removed [POST /share_profiles/listener/share_profile_removed]

+ Response 200 (application/json)
    + Attributes (Share profile)

## Data structures

### Share profile

+ id: 7453466 (number)
+ name: Videos only
+ str: `Videos only (default)`
+ `default`: true (boolean) - Specifies whether this is the default share profile
+ size: 74655272532 (number) - Total size of shared files in this profile in bytes
+ files: 24643 (number) - Total number of shared files in this profile

### Share profile basic

+ id: 7453466 (number)
+ str: `Videos only (default)`


# Group Share roots



## Share roots [/share_roots/roots]

### List share roots [GET]

Get a list of all shared root directories.

Required permission: *settings_view*

+ Response 200 (application/json)
    + Attributes (array[Share root])


## Share root [/share_roots/root]

### Create share root [POST]

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes (Share root request)
        + path: /home/airdcpp/share/Linux/Ubuntu 14.04/ (required) - Local directory path
    
+ Response 200 (application/json)
    + Attributes (Share root)

### Update share root [PATCH /share_roots/root/{root_id}]

Update the specified fields of a share root

Required permission: *settings_edit*

+ Request (application/json)
    + Attributes (Share root request)
    
+ Response 200 (application/json)
    + Attributes (Share root)

### Get share root [GET /share_roots/root/{root_id}]

Required permission: *settings_view*

Get a single root by ID.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (Share root)
    
### Remove share root [DELETE /share_roots/root/{root_id}]

Required permission: *settings_edit*

+ Response 204


## Subscriptions [/share_roots/listener]

Required permission: *settings_view*
    
### Share root created [POST /share_roots/listener/share_root_created]

+ Response 200 (application/json)
    + Attributes (Share root)

### Share root updated [POST /share_roots/listener/share_root_updated]

Only the updated properties are sent.

+ Response 200 (application/json)
    + Attributes (Share root)

### Share root created [POST /share_roots/listener/share_root_removed]

+ Response 200 (application/json)
    + Attributes (Share root)

## Data Structures


### Share root request

+ virtual_name: Ubuntu 14.04 (optional) - Directory name that is shown in the filelist. Multiple roots may be added with the same virtual name and they will be merged in filelist. If no virtual name is specified, it will be determined automatically from the path.
+ incoming: true (boolean, optional) - Set this root as incoming that can be configured to use a different refresh interval.
    + Default: false
+ profiles: 13, 5314 (array, optional) - List of share profiles to use for this root. If no share profile is specified, the default one will be added.

### Share root

+ id: 76NLOTOBZVTWXOHIWKCXB27W46ULOI7EAUZUTTI
+ path: /home/airdcpp/share/Linux/Ubuntu 14.04/ - Local directory path
+ virtual_name: Ubuntu 14.04 - Name to show in filelist
+ incoming: true (boolean) - Incoming roots can be configured to use a different refresh interval.
    + Default: false
+ profiles (array[Share profile basic])  - List of share profiles configured for this root.
+ type (Folder type)
+ size: 62523525626 (number) - Size in bytes
+ last_refresh_time: 1483611458 (number) - Time of last refresh
+ status
    + id (enum[string])
        + normal
        + refresh_pending
        + refresh_running
    + str: Normal


# Group System

## Methods [/system]

### Get away state [GET /system/away]

+ Response 200 (application/json)
    + Attributes (Away state)

### Set manual away state [POST /system/away]

+ Request (application/json)
    + Attributes
        + away: true (boolean, required)

+ Response 200 (application/json)
    + Attributes (Away state)


### Get stats [GET /system/stats]

+ Response 200 (application/json)
    + Attributes
        + server_threads: 4 (number) - Number of configured web server threads
        + active_session: 2 (number)


### Get system info [GET /system/system_info]

Get generic information about the application and the system it's running on

+ Response 200 (application/json)
    + Attributes (System info)


### Restart web server [POST /system/restart_web]

Required permission: *admin*

+ Response 204

### Shutdown application [POST /system/shutdown]

Required permission: *admin*

+ Response 204
    

## Subscriptions [/system/listener]

### Away state changed [POST /system/listener/away_state]

+ Response 200 (application/json)
    + Attributes (Away state)

## Data Structures

### Away state

+ id (enum[string])
    + off - Away mode is not enabled
    + idle - Idle away mode is enabled
    + manual - Manual away mode is enabled

### System info

+ cid: 76NLOTOBZVTWXOHIWKCXB27W46ULOI7EAUZUTTI - An unique application identifier
+ hostname: web-demo - System hostname
+ path_separator: / - System's native path separator character
+ client_version: `AirDC++w 2.0.0 x86_64` - Full application version string
+ client_started: 1483972366 - Time when the application was started
+ platform: other (enum[string])
  + windows
  + osx
  + other


# Group Transfers

Tranfer API manages download and upload connections.


## Transfers [/transfers/transfers]

### Get transfers [GET]

Required permission: *transfers*

+ Response 200 (application/json)
    + Attributes (array[Transfer item])


## Transfer [/transfers/transfer]

### Get transfer [GET /transfers/transfer/{id}]

Required permission: *transfers*

+ Response 200 (application/json)
    + Attributes (Transfer item)

### Disconnect transfer [POST /transfers/transfer/{id}/disconnect]

Disconnect a running transfer.

Required permission: *transfers*

+ Response 204

### Force connect [POST /transfers/transfer/{id}/force]

Attempt to establish connection instantly. Has no effect for running transfers.

Required permission: *transfers*

+ Response 204


## Generic methods [/transfers]

### Get transferred bytes [POST /transfers/tranferred_bytes]

+ Response 200 (application/json)
    + Attributes
        + session_downloaded: 5325235 (number)
        + session_uploaded 6768544233 (number)
        + start_total_downloaded: 5543652344 (number)
        + start_total_uploaded: 6433254263622 (number)
    

## Subscriptions [/transfers/listener]

Required permission: *transfers*

### Transfer added [POST /transfers/listener/transfer_added]

Only the values that have changed after the last event are sent.

+ Response 200 (application/json)
    + Attributes (Transfer item)

### Transfer updated [POST /transfers/listener/transfer_updated]

Only the updated properties are sent.

+ Response 200 (application/json)
    + Attributes (Transfer item)

### Transfer removed [POST /transfers/listener/transfer_removed]

+ Response 200 (application/json)
    + Attributes (Transfer item)

### Transfer statistics [POST /transfers/listener/transfer_statistics]

Only the values that have changed after the last event are sent.

+ Response 200 (application/json)
    + Attributes
        + speed_down: 0 (number)
        + speed_up: 754324 (number)
        + limit_down: 0 (number)
        + limit_up: 0 (number)
        + upload_bundles: 1 (number)
        + download_bundles: 0 (number)
        + uploads: 2 (number)
        + downloads: 0 (number)
        + session_downloaded: 5325235 (number)
        + session_uploaded 6768544233 (number)


## Data Structures

### Transfer item

+ id: 83425443
+ name: Ubuntu 14.04.iso - Local file name
+ target: /home/airdcpp/share/Ubuntu/Ubuntu 14.04.iso - Local file path
+ download: true (boolean) - Whether it's a download (false = upload)
+ type (File type) - Content type 'filelist' is also used here
+ size: 62523525626 (number) - Size in bytes
+ bytes_transferred: 4521124 (number)
+ time_started: 65235235 (number)
+ speed: 5234324 (number) - Current transfer speed, bytes per second
+ seconds_left: 632576 (number) - Seconds left based on the current transfer speed
+ encryption (Encryption)
+ ip (IP)
+ user (Hinted user)
+ status
    + id (enum[string])
        + waiting
        + finished
        + running
        + failed
    + str: `Running (42.3%)`
    + finished: false (boolean)
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y - File TTH
+ flags (array[Transfer flag])

### Transfer flag (enum[string])

+ M - MCN
+ S - Encryption, trusted certificate
+ U - Encryption, untrusted certificate
+ P - Partial bundle/file sharing
+ T - TTH validation is enabled (downloads only)
+ Z - Compressed file transfer
+ C - Chunked file transfer


# Group Users

## Ignores [/users/ignores]

### Get ignored users [GET]

Required permission: *settings_view*

+ Response 200 (application/json)
    + Attributes (array[User])
    

### Add ignored user [POST /users/ignore/{cid}]

Required permission: *settings_edit*

+ Response 204

    
### Remove ignored user [DELETE /users/ignore/{cid}]

Required permission: *settings_edit*

+ Response 204


## Miscellaneous [/users]

### Get user [GET /users/user/{cid}]

Get user by CID.

+ Response 200 (application/json)
    + Attributes (User)

### Search nicks [POST /users]

Search users with nick matching the provided pattern. The most relevant match is returned first.

+ Request (application/json)
    + Attributes
        + pattern: Share (required)
        + max_results: 5 (number, required)
        + hub_urls: adcs://myhub.com:6423, mynmdchub.com (array, optional) - A list of hub URLs where the users will be searched from. Defaults to all connected hubs.
        + ignore_prefixes: true (boolean, optional) - Ignore nick prefixes (eg. [0.5], [10]) when comparing match relevancies
            + Default: true

+ Response 200 (application/json)
    + Attributes (array[Hub user])

## Subscriptions [/users/listener]

Subscriptions related to connect state changes are tracked globally on per-user basis and sent users are not bound to any hub. If you want to track hub level user connect state changes, you should use the Hub API listeners instead.

### User connected [POST /users/listener/user_connected]

+ Response 200 (application/json)
    + Attributes
        + user (User)
        + was_offline: true (boolean) - true if the user wasn't online in any hub before this event

### User updated [POST /users/listener/user_updated]

+ Response 200 (application/json)
    + Attributes (User)

### User disconnected [POST /users/listener/user_disconnected]

+ Response 200 (application/json)
    + Attributes 
        + user (User)
        + went_offline: false (boolean) - true if the user isn't online in any hub

### Ignored user added [POST /users/listener/ignored_user_added]

+ Response 200 (application/json)
    + Attributes (User)

### Ignored user removed [POST /users/listener/ignored_user_removed]

+ Response 200 (application/json)
    + Attributes (User)



# Group Web users

## Web users [/web_users/users]

### List web users [GET]

Get a list of web users

Required permission: *admin*

+ Response 200 (application/json)
    + Attributes (array[Web user])


## Web user [/web_users/user]

### Create web user [POST]

Required permission: *admin*

+ Request (application/json)
    + Attributes
        + username: user1 (required)
        + password: userpassword (required)
        + permissions (array[Web permission], required) - List of permissions assigned for the user. Note: 'admin' permission gives access to all API methods.
    
+ Response 200 (application/json)
    + Attributes (Web user)

### Update web user [PATCH /web_users/user/{user_id}]

Update the specified fields of a web user

Required permission: *admin*

+ Request (application/json)
    + Attributes
        + password: userpassword
        + permissions (array[Web permission]) - List of permissions assigned for the user. Note: 'admin' permission gives access to all API methods.
    
+ Response 200 (application/json)
    + Attributes (Web user)

### Get web user [GET /web_users/user/{user_id}]

Required permission: *admin*

Get a single user by ID.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Web user)

### Remove web user [DELETE /web_users/user/{user_id}]

Required permission: *admin*

+ Response 204


## Subscriptions [/web_users/listener]

Required permission: *admin*
    
### Web user created [POST /web_users/listener/web_user_added]

+ Response 200 (application/json)
    + Attributes (Web user)

### Web user updated [POST /web_users/listener/web_user_updated]

+ Response 200 (application/json)
    + Attributes (Web user)

### Web user removed [POST /web_users/listener/web_user_removed]

+ Response 200 (application/json)
    + Attributes (Web user)

## Data Structures

### Web user

+ username: user1
+ permissions (array[Web permission]) - List of permissions assigned for the user. Note: 'admin' permission gives access to all API methods.
+ active_sessions: 1 (number)
+ last_login: 412412456 (number) - Time of the last successful login

### Web permission (enum[string])

+ admin - This permission gives access to all API features and not other permissions will be listed
+ download
+ search
+ transfers
+ favorite_hubs_view
+ favorite_hubs_edit
+ events_view
+ events_edit
+ filelists_view
+ filelists_edit
+ filesystem_view
+ filesystem_edit
+ hubs_view
+ hubs_edit
+ hubs_send
+ private_chat_view
+ private_chat_edit
+ private_chat_send
+ queue_edit
+ queue_view
+ settings_view
+ settings_edit
+ view_file_view
+ view_file_edit



# Group Viewed files

## Fetching file content

All viewed files that have completed downloading can be accessed via HTTP by using the following URL:

`http(s)://<server address>/view/<file id>`

Authentication information is required for accessing the file. 
You may use the regular HTTP authorization header or alternatively add the query *`?auth=<authorization>`* after the URL.

Example:

`http://localhost:5600/view/ZMT6DPFKQGNGWO6I5Y6FKRHJJSL73DI5YAFGB6I?auth=417886b3-7419-48f1-a541-f308947db011`

Warning: 

Due to limitations of the embedded web server, the whole file content will be loaded in memory before uploading. This may cause stability issues
on systems with low amount of memory. Therefore, it's recommended to use this API for viewing relatively small files.


## Viewed files [/view_files/sessions]

### Get a list of all viewed file [GET]

Required permission: *view_files_view*

+ Response 200 (application/json)
    + Attributes (array[View file])

## View file [/view_files/session]

### Open file from remote user [POST]

Open a new file from remote user. 

Required permission: *view_files_edit*

+ Request (application/json)
    + Attributes
        + name: Ubuntu 14.04.nfo (required) - File name (title)
        + size: 9552 (number, required) - Size in bytes
        + tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y (required) - File TTH
        + text: false (boolean, optional) - Is the file viewed as text
            + Default: false
        + user (Hinted user base, required)
+ Response 200 (application/json)
    + Attributes (View file)

### Open local file [POST /view_files/session/{tth}]

Open a file that exists in share. 

Required permission: *view_files_edit*

+ Request (application/json)
    + Attributes
        + text: false (boolean, optional) - Is the file viewed as text
            + Default: false
+ Response 200 (application/json)
    + Attributes (View file)

### Get file [GET /view_files/session/{file_id}]

Required permission: *view_files_view*

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (View file)

### Remove session [DELETE /view_files/session/{file_id}]

Required permission: *view_files_edit*

+ Response 204

### Set the file as read [POST /view_files/session/{file_id}/read]

Required permission: *view_files_view*

+ Response 204

### Get the content as text [GET /view_files/session/{file_id}/text]

Receive the content of the file as text. Using this method with files larger than 1 MB will return an error.

Required permission: *view_files_view*

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes
        + text: This is the file content


## Subscriptions [/view_files/listener]

Required permission: *hubs_view*

All subscriptions from hub entities are also available to be used across all sessions (add them with */hubs/listener/event_name*).

### File added [POST /hubs/listener/view_file_added]

+ Response 200 (application/json)

    + Attributes (View file)

### File updated [POST /hubs/listener/view_file_updated]

Download state was updated

+ Response 200 (application/json)

    + Attributes (View file)

### File finished [POST /hubs/listener/view_file_finished]

Fired when the file is ready for viewing

+ Response 200 (application/json)

    + Attributes (View file)

### File removed [POST /hubs/listener/view_file_removed]

+ Response 200 (application/json)
    + Attributes (View file)


## Data Structures

### View file

+ id: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y
+ name: Ubuntu 14.04.nfo
+ size: 9552 (number) - Size in bytes
+ type (File type)
+ tth: CUO74LMZUQMQCBR5UKTIFJPO32LVUH5VZBOL54Y - File TTH
+ text: false (boolean) - Is the file viewed as text
+ time_opened: 1483277168 (number) - Time when the file was opened for viewing
+ read: false (boolean) - Has the file been marked as read
+ download_state (Downloadable item state) - Current download state of the remote user file. Not available for local files.
+ content_ready: true (boolean) - Whether the file content is ready to be viewed







## Data Structures

### Grouped path

+ name: Videos
+ paths: /home/airdcpp/share/Videos/, /mnt/disk2/share/Videos/ (array[string])

### Search query

+ pattern: Ubuntu - Search string. All words must be found from the full file/directory path (partial match)
+ file_type (File content ID)
    + any
    + tth
    + directory
    + file
+ extensions: iso, img - Allowed file extensions (files only)
+ min_size: 50000000 - Minimum file size (files only)
+ max_size: 100000000 - Maximum file size (files only)
+ excluded: server, iot - List of strings that should not be found from the file/directory path (partial match)

### Download params (object)

+ target_name: Ubuntu (required)
+ target_directory: /home/airdcpp/share/ - Destination path where the bundle will be created. If no path is provided, the default download directory will be used.
+ priority (Queue priority ID, optional) - Bundle priority. Auto priority will be used if not specified.

### Downloadable item state

+ id (enum[string])
    + download_failed
    + download_pending
    + downloading
    + loading
    + downloaded
+ str: `Downloading (45.4%)`
+ time_finished: 0 (number) - Time when the item finished downloading (0 = not finished)

### Encryption

+ str: `TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256` - TLS version and cipher
+ trusted: false (boolean) - Indicates whether there's a matching keyprint set for the hub

### Dupe

+ id (enum[string])
    + share_partial
    + share_full
    + queue_partial - Bundle item that has not finished downloading yet
    + queue_full
    + finished_partial - Bundle item that has finished downloading
    + finished_full
    + share_queue
+ paths: /home/airdcpp/share/dir/, /mnt/disk2/dir/ - An array of local paths for this item

### Priority ID (enum[number])

+ 1 - Lowest
+ 2 - Low
+ 3 - Normal
+ 4 - High
+ 5 - Highest

### Queue priority ID (enum[number])

+ `-1` - `Paused (forced)`
+ 0 - Paused
+ 1 - Lowest
+ 2 - Low
+ 3 - Normal
+ 4 - High
+ 5 - Highest

### Item type (enum)

+ (Folder type)
+ (File type)

### File type

+ id: file
+ str: iso
+ content_type (File content ID)
    + other

### File content ID (enum[string])

+ audio
+ compressed
+ document
+ executable
+ picture
+ video

### Folder type

+ id: directory
+ str: `2 folders, 49 files`
+ files: 49 (number)
+ directories: 2 (number)




### Chat message info

+ total_count: 100 (number)
+ unread_counts (Unread chat info)

### Log message info

+ total_count: 100 (number)
+ unread_counts (Unread log info)

### Unread chat info

+ user: 2 (number) - Number of unread user messages
+ bot: 12 (number) - Number of unread bot messages
+ status: 0 (number) - Number of unread status messages

### Unread log info

+ info: 6 (number)
+ warning: 3 (number)
+ error: 1 (number)

### Chat message request

+ text: Hello there (required)
+ third_person: false (boolean, optional) - Indicate that the message was sent as third person (/me)
    + Default: false

### Status message request

+ text: `[10]APITester: ISO file(s) over 500 MB in share (/Ubuntu/Ubuntu 14.04.iso)` (required)
+ severity: info (Severity)

### Chat message

+ id: 1 (number)
+ time: 1483277168 (number)
+ text: Hello there
+ third_person: false (boolean)  - Indicate that the message was sent as third person (/me)
+ is_read: false (boolean)
+ from (Hub user) - Sender of the message
+ reply_to (Hub user, optional) - User to who the reply is being send to. This may differ from the the sender if the message was received from a bot/chatroom. This field is generally not available with hub messages.
+ to (Hub user, optional) - Receiver of the message. This is generally your own user unless the message was received from a bot/chatroom. This field is generally not available with hub messages.
    + nick: Developer
    + cid: 76NLOTOBZVTWXOHIWKCXB27W46ULOI7EAUZUTTI
    + description: Just writing scripts

### Status message

+ id: 2 (number)
+ time: 1483277168 (number)
+ text: `Connecting to adcs://myhub.com:6423 ...`
+ severity: info (Severity)
+ is_read: false (boolean)

### Severity (enum[string])

+ notify - Notify events are not stored by the application (they are generally real-time notifications related to a recent activity)
+ info
+ warning
+ error



### User

+ cid: NJSHVYR4ZHCZFUEZNGA7M2D72S5AB4WQAMPBKFA
+ nicks: `[Developer, [100]Developer]` 
+ hub_names: `[Demo hub, Dev hub]`
+ hub_urls: adcs://myhub.com:6423, adc://devhub.com:1234
+ flags (array[User flag])

### Hinted user base

+ cid: NJSHVYR4ZHCZFUEZNGA7M2D72S5AB4WQAMPBKFA
+ hub_url: adcs://myhub.com:6423 - URL of the hinted hub

### Hinted user (Hinted user base)

+ nicks: `Developer ([100]Developer)` - Nick in the hinted hub is shown first and possible other nicks are inside parentheses 
+ hub_names: `Demo hub (Dev hub)` - Name of the hinted hub is shown first and possible other hub names are inside parentheses 
+ flags (array[Hub user flag]) - Flags in the hinted hub. All flags are not displayed if the user is offline.

### Hub user (Hinted user base)

+ hub_name: Demo hub
+ flags (array[Hub user flag])
+ ip4 (object) - IPv4 address
    + country_id: NL - Netherlands
    + ip: 89.255.248.35
    + str: NL - Netherlands (89.255.248.35)
+ ip6 (IP) - IPv6 address
+ nick: Share
+ email: ""
+ share_size: 728128900 (number) - Share size (bytes)
+ upload_speed: 12500000 (number) - Upload speed (bytes/second)
+ download_speed: 12500000 (number) - Download speed (bytes/second, ADC users only)
+ file_count: 29 (number) - Total number of files shared by the user (ADC users only)
+ description: Demo share
+ tag: `<AirDC++w 1.3.1-44-g616c,M:P-,H:0/0/1,S:19>`

### IP

+ country: NL - Netherlands
+ ip: 2a00:1a48:1261::168
+ str: NL - Netherlands (2a00:1a48:1261::168)

### User flag (enum[string])

+ me - The user is me
+ bot - The user is a bot (ADC users only)
+ ascs - The user supports advanced searching extension (ADC users only)
+ ccpm - The user supports encrypted client-to-client private messaging (ADC users only)
+ ignored - Messages from this user are ignored
+ favorite - The user has been marked as favorite
+ nmdc - NMDC user
+ offline - The user is offline

### Hub user flag (User flag)

+ away - The user has away mode enabled
+ op - The user is an operator
+ hidden - The user is not visible in userlist
+ noconnect - It's not possible to establish transfer/CCPM connections to this user
+ passive - The user has passive connectivity mode configured